<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "biotranscost".
 *
 * @property int $id
 * @property string $name
 * @property string $price
 * @property string $image
 * @property string $buttonName
 */
class Biotranscost extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'biotranscost';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'price', 'image', 'buttonName'], 'required'],
            [['name', 'price', 'image', 'buttonName'], 'string', 'max' => 255],
            [['image'],'file','extensions'=>'svg']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'price' => 'Цена',
            'image' => 'Картинка',
            'buttonName' => 'Названия кнопка',
        ];
    }

    public function saveImage($filename)
    {
        $this->image = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->image) ? '/uploads/' . $this->image : '/no-image.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
